name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 23 * * *'  # 每天早上7点运行（UTC时间）

jobs:
  build:
    env:
      EMAIL: ${{ vars.EMAIL }}
      PASSWORD: ${{ vars.PASSWORD }}
      BASE_URL: ${{ vars.BASE_URL }}
      SCKEY: ${{ vars.SCKEY }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the application
      run: |
        python main.py
